
spring:
  application:
    name: HotelService
  config:
    import: "optional:configserver:http://localhost:8085"

  datasource:
    url: jdbc:mysql://localhost:3306/microservice2
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082



#set in the github configuration
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

