spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ohmprakashganesh/Configuration-microservice
          clone-on-start: true
server:
  port: 8085

   