spring:
  application:
    name: USERSERVICE


  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

   


