


spring:
  application:
    name: USERSERVICE
  config:
    import: "optional:configserver:http://localhost:8085"
  # profiles:
  #   active: prod


  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080






   


